version: '3.9'

services:
  productservice:
    build: ./productservice
    container_name: productservice
    ports: 
      - '5000:5000'
    depends_on: 
      - 'db'
  db:
    image: 'postgres:13-alpine'
    restart: always
    container_name: postgre-db
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 123
    volumes: 
      - data:/var/lib/postgresql/data
      - ./sql/create-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-table.sql:/docker-entrypoint-initdb.d/fill_table.sql

volumes: 
  data: