version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  krakend:
    image: devopsfaith/krakend:1.3.0
    container_name: krakend
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - fake_api
    networks:
      - app-tier

  catalogservice:
    build: ./productservice
    container_name: catalogservice
    ports:
      - '5000:5000'
    depends_on:
      - 'catalog-db'
    networks:
      - app-tier

  cartservice:
    build: ./cartservice
    container_name: cartservice
    ports:
      - '5001:5001'
    depends_on:
      - 'redis'
    command: go run .
    networks:
      - app-tier

  identityservice:
    build:
      ./identityservice
    container_name: identityservice
    ports:
      - '5002:5002'
    depends_on:
      - 'user-db'
    networks:
      - app-tier

  checkoutservice:
    build: ./checkoutservice
    container_name: checkoutservice
    ports:
    - '5003:5003'
    depends_on:
      - 'rabbitmq'
    networks:
      - app-tier
      
  paymentservice:
    build: ./paymentservice
    container_name: paymentservice
    ports:
    - '5004:5004'
    depends_on:
      - 'rabbitmq'
    networks:
      - app-tier

  emailservice:
    build: ./emailsercice
    container_name: emailservice
    ports:
    - '5005:5005'
    depends_on:
      - 'rabbitmq'
    networks:
      - app-tier

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
    - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    - ./rabbitmq/logs:/var/log/rabbitmq/log
    networks:
      - app-tier

  user-db:
    image: 'postgres:13-alpine'
    restart: always
    container_name: user-db
    ports:
      - '5960:5432'
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - identity-data:/var/lib/postgresql/data
      - ./sql/create-user-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-user-table.sql:/docker-entrypoint-initdb.d/fill_table.sql
    networks:
      - app-tier

  catalog-db:
    image: 'postgres:13-alpine'
    restart: always
    container_name: catalog-db
    ports:
      - '5961:5432'
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - catalog-data:/var/lib/postgresql/data
      - ./sql/create-product-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-product-table.sql:/docker-entrypoint-initdb.d/fill_table.sql
    networks:
      - app-tier

  fake_api:
    image: jaxgeller/lwan
    container_name: fake_api
    volumes:
      - ./file_server:/lwan/wwwroot
    ports:
      - "8000:8080"
    networks:
      - app-tier

  redis:
    image: 'redis:alpine'
    container_name: redis_cache
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - app-tier

volumes:
  catalog-data:
  identity-data:
