version: '3.9'

services:
  krakend:
    image: devopsfaith/krakend:1.3.0
    container_name: krakend
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - fake_api

  productservice:
    build: ./productservice
    container_name: productservice
    ports:
      - '5000:5000'
    depends_on:
      - 'database'

  identityservice:
    build:
      ./identityservice
    container_name: identityservice
    ports:
    - '5002:5002'
    depends_on:
      - 'database'

  database:
    image: 'postgres:13-alpine'
    restart: always
    container_name: database
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/create-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-table.sql:/docker-entrypoint-initdb.d/fill_table.sql

  fake_api:
    image: jaxgeller/lwan
    container_name: fake_api
    volumes:
      - ./file_server:/lwan/wwwroot
    ports:
      - "8000:8080"

volumes:
  data: