version: '3.9'

services:
  krakend:
    image: devopsfaith/krakend:1.3.0
    container_name: krakend
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - fake_api

  catalogservice:
    build: ./productservice
    container_name: catalogservice
    ports:
      - '5000:5000'
    depends_on:
      - 'catalog-db'

  cartservice:
    build: ./cartservice
    container_name: cartservice
    ports:
      - '5001:5001'
    depends_on:
      - 'redis'
    command: go run .

  identityservice:
    build:
      ./identityservice
    container_name: identityservice
    ports:
      - '5002:5002'
    depends_on:
      - 'user-db'

  user-db:
    image: 'postgres:13-alpine'
    restart: always
    container_name: user-db
    ports:
      - '5960:5432'
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - identity-data:/var/lib/postgresql/data
      - ./sql/create-user-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-user-table.sql:/docker-entrypoint-initdb.d/fill_table.sql

  catalog-db:
    image: 'postgres:13-alpine'
    restart: always
    container_name: catalog-db
    ports:
      - '5961:5432'
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - catalog-data:/var/lib/postgresql/data
      - ./sql/create-product-table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/fill-product-table.sql:/docker-entrypoint-initdb.d/fill_table.sql

  fake_api:
    image: jaxgeller/lwan
    container_name: fake_api
    volumes:
      - ./file_server:/lwan/wwwroot
    ports:
      - "8000:8080"

  redis:
    image: 'redis:alpine'
    container_name: redis_cache
    ports:
      - '6379:6379'
    restart: unless-stopped


volumes:
  catalog-data:
  identity-data:
